namespace Pangya_GameServer.Models;

public enum eBROADCAST_TYPES : byte
{
	BT_HIDE_BROADCAST = 0,
	BT_SPINNING_CUBE_RARE = 1,
	BT_SPINNING_CUBE_WIN_PANG_POUCH = 2,
	BT_GOLDEN_TIME_START_OF_DAY = 11,
	BT_GOLDEN_TIME_START_ROUND = 12,
	BT_GOLDEN_TIME_ROUND_MORE_PEOPLE = 13,
	BT_GOLDEN_TIME_ROUND_REWARD_PLAYER = 14,
	BT_GOLDEN_TIME_FINISH_ROUND = 15,
	BT_GOLDEN_TIME_FINISH_OF_DAY = 16,
	BT_GOLDEN_TIME_FINISH = 17,
	BT_GOLDEN_TIME_ROUND_NOT_HAVE_WINNERS = 18,
	BT_MESSAGE_PLAIN = 20,
	BT_GRAND_ZODIAC_EVENT_START_TIME = 21
}
